// Generated by CoffeeScript 1.4.0
(function() {

  module("APP.Core");

  test("Config", function() {
    expect(4);
    equal(typeof APP.Core.Config.get(), "object");
    equal(typeof APP.Core.Config.get("nonExisting"), "undefined");
    equal(typeof APP.Core.Config.set({
      key: "value"
    }), "object");
    equal(APP.Core.Config.get("key"), "value");
  });

}).call(this);
