// Generated by CoffeeScript 1.4.0
(function() {

  module("APP.Core");

  test("Config", function() {
    expect(4);
    return equal(typeof APP.Core.Config.get(), "object", "Get configuration");
  });

}).call(this);
