// Generated by CoffeeScript 1.4.0
(function() {

  module('APP.PubSub');

  test('on', function() {
    var testOn;
    testOn = false;
    APP.PubSub.on('news', function() {
      return testOn = true;
    });
    APP.PubSub.trigger('news');
    expect(1);
    return ok(testOn);
  });

  test('trigger', function() {
    var testTrigger;
    testTrigger = false;
    APP.PubSub.on('news', function(str) {
      return testTrigger = str;
    });
    APP.PubSub.trigger('news', 'value');
    expect(1);
    return equal(testTrigger, 'value');
  });

  test('off', function() {
    var testOff;
    testOff = false;
    APP.PubSub.on('news', function() {
      return testOff = true;
    });
    APP.PubSub.off('news');
    APP.PubSub.trigger('news');
    expect(1);
    return equal(testOff, false);
  });

}).call(this);
