// Generated by CoffeeScript 1.4.0
(function() {

  window.APP = (function(win, doc) {
    "use strict";

    var Config, Events, Log, Url, defaults, extend, module;
    defaults = {
      baseUri: "",
      debug: false,
      stopMethod: "start",
      startMethod: "stop",
      delimiter: "."
    };
    extend = function(obj, src) {
      var key;
      for (key in src) {
        if (src.hasOwnProperty(key)) {
          obj[key] = src[key];
        }
      }
      return obj;
    };
    Config = (function() {
      var config;
      config = extend({}, defaults);
      return {
        get: function(key) {
          if (!key) {
            return config;
          }
          return config[key];
        },
        set: function(key, value) {
          if (typeof key === "object") {
            config = extend(config, key);
          }
          config[key] = value;
          return config;
        }
      };
    })();
    Events = (function() {
      return {
        bind: function(el, e, fn) {
          if (el.addEventListener) {
            return el.addEventListener(e, fn, false);
          } else if (el.attachEvent) {
            return el.attachEvent("on" + e, fn);
          }
        },
        unbind: function(el, e, fn) {
          if (el.removeEventListener) {
            return el.removeEventListener(e, fn, false);
          } else if (el.detachEvent) {
            return el.detachEvent("on" + e, fn);
          }
        }
      };
    })();
    Log = (function() {
      return {
        history: [],
        write: function() {
          var arg, _i, _len;
          for (_i = 0, _len = arguments.length; _i < _len; _i++) {
            arg = arguments[_i];
            Log.history.push(arg);
          }
          if (win.hasOwnProperty(console) && Config.get("debug")) {
            return win.console.log(arguments);
          }
        }
      };
    })();
    Url = (function() {
      var strip;
      strip = function(str) {
        return str.replace(/^\/|\/$/g, "");
      };
      return {
        base: function() {
          var slash;
          if (strip(Config.get("baseUri"))) {
            slash = "/";
          }
          return [win.location.protocol, "//", win.location.host, slash, strip(Config.get("baseUri"))].join("");
        },
        site: function(uri) {
          return [Url.base(), "/", strip(uri)].join("");
        }
      };
    })();
    module = (function() {
      var getModuleName, getNamespace, namespaceFactory;
      getModuleName = function(str) {
        return str.split(Config.get("delimiter")).pop();
      };
      getNamespace = function(namespace) {
        var ns;
        ns = namespace.split(Config.get("delimiter")).slice(0, -1);
        return namespaceFactory(ns.join(Config.get("delimiter")));
      };
      namespaceFactory = function(namespace) {
        var mod, obj, _i, _len, _ref;
        obj = win;
        _ref = namespace.split(Config.get("delimiter"));
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          mod = _ref[_i];
          obj[mod] = obj[mod] || {};
          obj = obj[mod];
        }
        return obj;
      };
      return function(namespace, dependencies, callback) {
        var mn, ns;
        if (typeof callback === "undefined") {
          callback = dependencies;
          dependencies = [];
        }
        ns = getNamespace(namespace);
        mn = getModuleName(namespace);
        module = (typeof callback === "function" ? callback.apply(this, dependencies) : callback);
        ns[mn] = module;
        if (typeof module === "object") {
          return ns[mn] = extend(ns[mn] || {}, module);
        }
      };
    })();
    win.log = Log.write;
    return {
      module: module,
      Core: {
        Config: Config,
        Events: Events,
        Log: Log,
        Url: Url
      }
    };
  })(window, document);

}).call(this);
