// Generated by CoffeeScript 1.4.0
(function() {

  APP.module('APP.PubSub', function() {
    'use strict';

    var subscriptions;
    subscriptions = {};
    return {
      off: function(topic) {
        if (typeof topic === !'string') {
          throw new Error('Topic must be a string');
        }
        return subscriptions[topic] = [];
      },
      on: function(topic, fn) {
        if (typeof topic === !'string') {
          throw new Error('Topic must be a string');
        }
        if (typeof topic === !'function') {
          throw new Error('Callback must be a function');
        }
        if (typeof subscriptions[topic] === 'undefined') {
          subscriptions[topic] = [];
        }
        return subscriptions[topic].push(fn);
      },
      trigger: function(topic, args) {
        var t, _results;
        if (typeof topic === !'string') {
          throw new Error('Topic must be a string');
        }
        _results = [];
        for (t in subscriptions[topic]) {
          if (subscriptions[topic].hasOwnProperty(t)) {
            _results.push(subscriptions[topic][t](args));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };
  });

}).call(this);
